let types = {
  ERROR: "ERROR",
  ACCOUNT_ERROR: "ACCOUNT_ERROR",
  GET_USER: "GET_USER",
  PRINT: "PRINT",
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  LOG_IN_SUCCESSFULL: "LOG_IN_SUCCESSFULL",
  REGISTER_SEUCCESSFULL: "REGISTER_SEUCCESSFULL",
  ADD_COOKIE: "ADD_COOKIE",
}

module.exports = types
