let types = {
  ERROR: "ERROR",
  ACCOUNT_ERROR: "ACCOUNT_ERROR",
  GET_USER: "GET_USER",
  PRINT: "PRINT",
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  LOG_IN_SUCCESSFULL: "LOG_IN_SUCCESSFULL",
  REGISTER_SEUCCESSFULL: "REGISTER_SEUCCESSFULL",
  SET_COOKIE: "SET_COOKIE",
  GET_SESSION: "GET_SESSION",
  SET_SESSION: "SET_SESSION",
}

module.exports = types
